backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "static/images/uploads"
public_folder: "images/uploads"
collections:
  - label: "Seite"
    name: "page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { name: "path", label: "URL", widged: "string" }
      - { label: "Titel", name: "title", widged: "string" }
      - label: "Motto"
        name: "motto"
        widget: "list"
        allow_add: false
        fields:
          - { label: "Text", name: "text", widget: "text" }
          - label: "Größe"
            name: "size"
            widget: "select"
            options:
              - { label: "Klein", value: "small" }
              - { label: "Medium", value: "medium" }
              - { label: "Groß", value: "big" }
          - label: "Farbe"
            name: "color"
            widget: "select"
            options:
              - { label: "Zeiss-Blau", value: "primary" }
              - { label: "Hochschuhl-Blau", value: "secondary" }
              - { label: "Cyan", value: "tertiary" }
        default:
          - { text: "Wissen.", size: "medium", color: "primary" }
          - { text: "Schafft.", size: "medium", color: "tertiary" }
          - { text: "Spass!", size: "big", color: "secondary" }
      - label: "Featured Images"
        name: "thumbnailUrls"
        widget: "list"
        field: { label: "Bild", name: "image", widget: "image" }
      - label: "Breadcrumbs"
        name: "breadcrumbs"
        widget: "list"
      - label: "Seiten Abschnitte"
        name: "pageSections"
        widget: "list"
        types:
          - label: "Große Überschrift"
            name: "bigHeaderSection"
            widget: "object"
            summary: "{{fields.text}}"
            fields:
              - { label: "Überschrift", name: "text", widget: "text", default: "Große Überschrift" }
          - label: "Großer Text"
            name: "bigTextSection"
            widget: "object"
            summary: "{{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "text", default: "Großer Text" }
          - label: "Überschrift"
            name: "headerOnlySection"
            widget: "object"
            fields:
              - { label: "Haupt-Überschrift", name: "mainHeader", widget: "text", default: "Haupt-Überschrift" }
              - { label: "Unter-Überschrift", name: "subHeader", widget: "text", default: "Unter-Überschrift" }
              - { label: "Trennstrich", name: "divider", widget: "boolean", default: true }
          - label: "Abschnitt mit Spalten"
            name: "columnSection"
            widget: "object"
            fields:
              - label: "Überschrift"
                name: "header"
                widget: "object"
                fields:
                  - { label: "Haupt-Überschrift", name: "mainHeader", widget: "text", default: "Haupt-Überschrift" }
                  - { label: "Unter-Überschrift", name: "subHeader", widget: "text", default: "Unter-Überschrift" }
                  - { label: "Trennstrich", name: "divider", widget: "boolean", default: true }
              - label: "Hintergrundfarbe"
                name: "backgroundColor"
                widget: "color"
                required: false
                allowInput: true
              - { label: "Spaltenanzahl", name: "numberColumns", widget: "number", default: 2 }
              - label: "Spalten"
                name: "columns"
                widget: "list"
                types:
                  - label: "Bild"
                    name: "image"
                    widget: "object"
                    fields:
                      - { label: "Bild", name: "imageUrl", widget: "image" }
                      - { label: "Alternativ Text", name: "altText", widget: "text" }
                  - label: "Paragraph"
                    name: "paragraph"
                    widget: "object"
                    fields:
                      - { label: "Text", name: "text", widget: "markdown" }
                  - label: "Trennstrich"
                    name: "divider"
                    widget: "object"
                    fields:
                      - { label: "Trennstrich", name: "divider", widget: "hidden", default: true }
          - label: "Icon Blasen Abschnitt"
            name: "bubbleSection"
            widget: "object"
            fields:
              - { label: "Spaltenanzahl", name: "numberColumns", widget: "number", default: 2 }
              - label: "Hintergrundfarbe"
                name: "backgroundColor"
                widget: "color"
                required: false
                allowInput: true
              - label: "Blasen"
                name: "bubbles"
                widget: "list"
                fields:
                  - { label: "Text", name: "text", widget: "text", default: "Text" }
                  - label: "Bild"
                    name: "imageUrl"
                    widget: "image"
                  - label: "Farbe"
                    name: "color"
                    widget: "select"
                    options:
                      - { label: "Zeiss-Blau", value: "primary" }
                      - { label: "Hochschuhl-Blau", value: "secondary" }
                      - { label: "Cyan", value: "tertiary" }
                  - { label: "Link", name: "href", widget: "string", required: false }
          - label: "Porträts Abschnitt"
            name: "gridSection"
            widget: "object"
            fields:
              - label: "Elemente"
                name: "items"
                widget: "list"
                summary: "{{fields.altText}}"
                fields:
                  - { label: "Bild", name: "imageUrl", widget: "image" }
                  - { label: "Alternativ Text", name: "altText", widget: "text" }
                  - { label: "Beschreibung", name: "description", widget: "markdown" }
