backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "static/images/uploads"
public_folder: "images/uploads"
collections:
  - label: "Seite"
    name: "page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { name: "path", label: "URL", widget: "string" }
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Motto"
        name: "motto"
        widget: "list"
        allow_add: false
        fields:
          - { label: "Text", name: "text", widget: "text" }
          - label: "Größe"
            name: "size"
            widget: "select"
            options:
              - { label: "Klein", value: "small" }
              - { label: "Medium", value: "medium" }
              - { label: "Groß", value: "big" }
          - label: "Farbe"
            name: "color"
            widget: "select"
            options:
              - { label: "Zeiss-Blau", value: "primary" }
              - { label: "Hochschuhl-Blau", value: "secondary" }
              - { label: "Cyan", value: "tertiary" }
        default:
          - { text: "Wissen.", size: "medium", color: "primary" }
          - { text: "Schafft.", size: "medium", color: "tertiary" }
          - { text: "Spass!", size: "big", color: "secondary" }
      - label: "Featured Images"
        name: "thumbnailUrls"
        widget: "list"
        field: { label: "Bild", name: "image", widget: "image" }
      - label: "Breadcrumbs"
        name: "breadcrumbs"
        widget: "list"
      - label: "Seiten Abschnitte"
        name: "pageSections"
        widget: "list"
        types:
          - label: "Abstandshalter"
            name: "spacerSection"
            widget: "object"
            fields:
              - { label: "Abstandshalter", name: "spacer", widget: "hidden", default: true }
          - label: "Große Überschrift"
            name: "bigHeaderSection"
            widget: "object"
            summary: "{{fields.text}}"
            fields:
              - { label: "Überschrift", name: "text", widget: "text", default: "Große Überschrift" }
          - label: "Großer Text"
            name: "bigTextSection"
            widget: "object"
            summary: "{{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "text", default: "Großer Text" }
          - label: "Überschrift"
            name: "headerOnlySection"
            widget: "object"
            summary: "{{fields.mainHeader}}"
            fields:
              - { label: "Haupt Überschrift", name: "mainHeader", widget: "text", default: "Haupt Überschrift" }
              - { label: "Unter Überschrift", name: "subHeader", widget: "text", default: "Unter Überschrift", required: false }
              - { label: "Id (zum verlinken)", name: "sectionId", widget: "string", required: false }
              - { label: "Trennstrich", name: "divider", widget: "boolean", default: true }
          - label: "Abschnitt mit Spalten"
            name: "columnSection"
            widget: "object"
            summary: "{{fields.header.mainHeader}}"
            fields:
              - label: "Überschrift"
                name: "header"
                widget: "object"
                fields:
                  - { label: "Haupt Überschrift", name: "mainHeader", widget: "text", default: "Haupt Überschrift", required: false }
                  - { label: "Unter Überschrift", name: "subHeader", widget: "text", default: "Unter Überschrift", required: false }
                  - { label: "Id (zum verlinken)", name: "sectionId", widget: "string", required: false }
                  - { label: "Trennstrich", name: "divider", widget: "boolean", default: true }
              - label: "Hintergrundfarbe"
                name: "backgroundColor"
                widget: "color"
                required: false
                allowInput: true
              - { label: "Spaltenanzahl", name: "numberColumns", widget: "number", default: 2 }
              - label: "Spalten"
                name: "columns"
                widget: "list"
                types:
                  - label: "Bild"
                    name: "image"
                    widget: "object"
                    fields:
                      - { label: "Bild", name: "imageUrl", widget: "image" }
                      - { label: "Alternativ Text", name: "altText", widget: "text" }
                      - { label: "Breite in Spalten", name: "width", widget: "number", default: 1 }
                  - label: "Paragraph"
                    name: "paragraph"
                    widget: "object"
                    fields:
                      - { label: "Text", name: "text", widget: "markdown" }
                      - { label: "Breite in Spalten", name: "width", widget: "number", default: 1 }
                  - label: "Trennstrich"
                    name: "divider"
                    widget: "object"
                    fields:
                      - { label: "Trennstrich", name: "divider", widget: "hidden", default: true }
                  - label: "Karte"
                    name: "card"
                    widget: "object"
                    fields:
                      - label: "Überschrift"
                        name: "header"
                        widget: "object"
                        fields:
                          - { label: "Überschrift", name: "header", widget: "markdown", default: "# Überschrift" }
                          - { label: "Id (zum verlinken)", name: "anchorId", widget: "string", required: false }
                          - { label: "Bild", name: "imageUrl", widget: "image", required: false }
                          - { label: "Alternativ Text", name: "altText", widget: "text", required: false }
                      - { label: "Breite in Spalten", name: "width", widget: "number", default: 1 }
                      - { label: "Spaltenanzahl", name: "numberColumns", widget: "number", default: 1 }
                      - label: "Spalten"
                        name: "columns"
                        widget: "list"
                        types:
                          - label: "Bild"
                            name: "image"
                            widget: "object"
                            fields:
                              - { label: "Bild", name: "imageUrl", widget: "image" }
                              - { label: "Alternativ Text", name: "altText", widget: "text" }
                          - label: "Paragraph"
                            name: "paragraph"
                            widget: "object"
                            fields:
                              - { label: "Text", name: "text", widget: "markdown" }
                          - label: "Trennstrich"
                            name: "divider"
                            widget: "object"
                            fields:
                              - { label: "Trennstrich", name: "divider", widget: "hidden", default: true }
          - label: "Icon Blasen Abschnitt"
            name: "bubbleSection"
            widget: "object"
            fields:
              - { label: "Spaltenanzahl", name: "numberColumns", widget: "number", default: 2 }
              - label: "Hintergrundfarbe"
                name: "backgroundColor"
                widget: "color"
                required: false
                allowInput: true
              - label: "Blasen"
                name: "bubbles"
                widget: "list"
                fields:
                  - { label: "Text", name: "text", widget: "text", default: "Text" }
                  - label: "Bild"
                    name: "imageUrl"
                    widget: "image"
                  - label: "Farbe"
                    name: "color"
                    widget: "select"
                    options:
                      - { label: "Zeiss-Blau", value: "primary" }
                      - { label: "Hochschuhl-Blau", value: "secondary" }
                      - { label: "Cyan", value: "tertiary" }
                  - { label: "Link", name: "href", widget: "string", required: false }
          - label: "Porträts Abschnitt"
            name: "gridSection"
            widget: "object"
            fields:
              - label: "Elemente"
                name: "items"
                widget: "list"
                summary: "{{fields.altText}}"
                fields:
                  - { label: "Bild", name: "imageUrl", widget: "image" }
                  - { label: "Alternativ Text", name: "altText", widget: "text" }
                  - { label: "Beschreibung", name: "description", widget: "markdown" }
          - label: "Banner Abschnitt"
            name: "bannerSection"
            widget: "object"
            summary: "{{fields.mainText}}"
            fields:
              - label: "Farbe"
                name: "color"
                widget: "select"
                default: "tertiary"
                options:
                  - { label: "Zeiss-Blau", value: "primary" }
                  - { label: "Hochschuhl-Blau", value: "secondary" }
                  - { label: "Cyan", value: "tertiary" }
              - { label: "Haupt-Text", name: "mainText", widget: "text", default: "Erste Zeile\nzweite Zeile" }
              - { label: "Unter-Text", name: "subText", widget: "text", default: "Beschreibung" }
              - { label: "Link", name: "href", widget: "string", required: false }
          - label: "Workshops Abschnitt"
            name: "workshopsSection"
            widget: "object"
            fields:
              - label: "Hintergrundfarbe"
                name: "backgroundColor"
                widget: "color"
                required: false
                allowInput: true
              - label: "Workshops"
                name: "workshops"
                widget: "list"
                summary: "{{fields.workshop}}"
                field:
                  label: "Workshop"
                  name: "workshop"
                  widget: "relation"
                  collection: "workshop"
                  search_fields: ["title", "header", "footer"]
                  value_field: "/{{slug}}"
                  display_fields: ["title"]
          - label: "Akkordeon Abschnitt"
            name: "accordionSection"
            widget: "object"
            fields:
              - label: "Elemente"
                name: "items"
                widget: "list"
                summary: "{{fields.header}}"
                fields:
                  - { label: "Überschrift", name: "header", widget: "text", default: "Überschrift" }
                  - { label: "Text", name: "text", widget: "markdown" }
  - label: "Workshop"
    name: "workshop"
    folder: "content/workshops"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Überschrift", name: "header", widget: "markdown", default: "# Überschrift" }
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "object"
        fields:
          - { label: "Bild", name: "imageUrl", widget: "image" }
          - { label: "Alternativ Text", name: "altText", widget: "text" }
      - { label: "Spaltenanzahl", name: "numberColumns", widget: "number", default: 2 }
      - label: "Spalten"
        name: "columns"
        widget: "list"
        types:
          - label: "Bild"
            name: "image"
            widget: "object"
            fields:
              - { label: "Bild", name: "imageUrl", widget: "image" }
              - { label: "Alternativ Text", name: "altText", widget: "text" }
          - label: "Paragraph"
            name: "paragraph"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Trennstrich"
            name: "divider"
            widget: "object"
            fields:
              - { label: "Trennstrich", name: "divider", widget: "hidden", default: true }
      - { label: "Fußzeile", name: "footer", widget: "markdown", default: "Altersgruppe\nDauer\nWorkshop Leiter\nFachbereiche" }
  - label: "Artikel"
    name: "article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "slug", name: "slug", widget: "hidden", default: "{{slug}}" }
      - label: "Erstelldatum"
        name: "creationDate"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: true
        time_format: false
      - { label: "Überschrift", name: "mainHeader", widget: "text", default: "Überschrift" }
      - { label: "Unter Überschrift", name: "subHeader", widget: "text", default: "Unter Überschrift", required: false }
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "object"
        required: false
        fields:
          - { label: "Bild", name: "imageUrl", widget: "image", required: false }
          - { label: "Alternativ Text", name: "altText", widget: "text", required: false }
      - { label: "Einführung / Zusammenfassung", name: "introduction", widget: "markdown", default: "Einführung", required: false }
      - { label: "Text", name: "text", widget: "markdown" }
  - label: "Einstellungen"
    name: "settings"
    extension: "json"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "content/navigation.json"
        fields:
          - label: "Kategorien"
            name: "categories"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
                default: "Kategorie"
              - label: "Kategorie Link"
                name: "href"
                widget: "string"
                required: false
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                    default: "Link"
                  - label: "Link"
                    name: "href"
                    widget: "string"
                    default: "/"